// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awljihtqvvhabvtmlfvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bGppaHRxdnZoYWJ2dG1sZnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjQyMjAsImV4cCI6MjA2NzIwMDIyMH0.t1HbQEMKPOVRX4AXRntr-CXfVmH8Eyc93RV2o0LKhys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});